map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.0

transform_tolerance: 0.15

#footprint: [[-0.1, 0.3], [0.1, 0.3], [2.25, 0.15], [2.25, -0.15], [0.1, -0.3], [-0.1, 0.3]]
robot_radius: 0.5
inflation_radius: 1.0
cost_scaling_factor: 3.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
