global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 20.0
   publish_frequency: 20.0
   width: 20.0
   height: 20.0
   resolution: 0.02
   static_map: true
   rolling_window: false